version: "3.5"

services:
  traefik:
    image: traefik:v2.2
    container_name: traefik
    domainname: docker
    hostname: traefik
    networks:
      - pihole
      - default
    dns:
      - 172.20.0.2
    ports:
      # The HTTP/HTTPS port
      - "80:80"
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart: unless-stopped
    command:
      # Enable Docker provider
      - "--providers.docker=true"
      # Defines the Docker network to use for connections to all containers
      - "--providers.docker.network=pihole"
      # This is false so I can selectively add apps into Traefik
      - "--providers.docker.exposedbydefault=false"
      # Enable insecure mode to access dashboard at :8080/dashboard
      - "--api.insecure=true"
      - "--api.dashboard=true"
      # Routing
      - "--entrypoints.web.address=:80"
      # Logging
      - "--log.level=DEBUG"

networks:
  pihole:
    ipam:
      config:
        - subnet: 172.20.0.0/24
